name: weather_app
description: A new Flutter project.
 
publish_to: 'none'  

 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^0.1.3
  flutter_svg: ^0.19.0
  google_fonts: ^1.1.0
  geolocator: ^3.0.1
  weather_icons: ^2.0.1
  intl: ^0.16.1
  futuristic: ^0.1.3
  fluttertoast: ^7.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

 

 
flutter:

   
  uses-material-design: true

  
  assets:
    - images/
  
     

   